name: 'Distill Analyze'
description: 'Analyze codebase for token optimization opportunities'
author: 'Distill'
branding:
  icon: 'zap'
  color: 'blue'

inputs:
  patterns:
    description: 'Comma-separated glob patterns to analyze'
    required: false
    default: '**/*.{ts,tsx,js,jsx,py,go,rs}'
  threshold:
    description: 'Token threshold for warnings (files above this are flagged)'
    required: false
    default: '2000'
  fail-on-threshold:
    description: 'Fail the action if any file exceeds threshold'
    required: false
    default: 'false'
  output-file:
    description: 'Path to write JSON report (optional)'
    required: false
    default: ''

outputs:
  total-files:
    description: 'Number of files analyzed'
  total-tokens:
    description: 'Total tokens across all files'
  files-above-threshold:
    description: 'Number of files exceeding token threshold'
  report-path:
    description: 'Path to generated JSON report (if output-file was set)'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install distill-mcp
      shell: bash
      run: npm install -g @anthropic-ai/distill-mcp

    - name: Run analysis
      id: analyze
      shell: bash
      run: |
        OUTPUT_ARGS=""
        if [ -n "${{ inputs.output-file }}" ]; then
          OUTPUT_ARGS="--output ${{ inputs.output-file }} --json"
        fi

        distill-mcp analyze \
          --patterns "${{ inputs.patterns }}" \
          --threshold ${{ inputs.threshold }} \
          $OUTPUT_ARGS \
          --json > /tmp/distill-report.json 2>&1 || true

        # Parse results
        if [ -f /tmp/distill-report.json ]; then
          TOTAL_FILES=$(jq -r '.totalFiles // 0' /tmp/distill-report.json)
          TOTAL_TOKENS=$(jq -r '.totalTokens // 0' /tmp/distill-report.json)
          FILES_ABOVE=$(jq -r '.filesAboveThreshold // 0' /tmp/distill-report.json)

          echo "total-files=$TOTAL_FILES" >> $GITHUB_OUTPUT
          echo "total-tokens=$TOTAL_TOKENS" >> $GITHUB_OUTPUT
          echo "files-above-threshold=$FILES_ABOVE" >> $GITHUB_OUTPUT

          # Print summary
          echo "## Token Analysis Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Files Analyzed | $TOTAL_FILES |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Tokens | $TOTAL_TOKENS |" >> $GITHUB_STEP_SUMMARY
          echo "| Above Threshold (${{ inputs.threshold }}) | $FILES_ABOVE |" >> $GITHUB_STEP_SUMMARY

          # List files above threshold
          if [ "$FILES_ABOVE" -gt 0 ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Files Exceeding Threshold" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            jq -r '.files[] | select(.exceedsThreshold) | "- \(.file): \(.tokens) tokens"' /tmp/distill-report.json >> $GITHUB_STEP_SUMMARY
          fi
        fi

        # Copy to output file if specified
        if [ -n "${{ inputs.output-file }}" ]; then
          cp /tmp/distill-report.json "${{ inputs.output-file }}"
          echo "report-path=${{ inputs.output-file }}" >> $GITHUB_OUTPUT
        fi

    - name: Check threshold
      if: inputs.fail-on-threshold == 'true'
      shell: bash
      run: |
        FILES_ABOVE="${{ steps.analyze.outputs.files-above-threshold }}"
        if [ "$FILES_ABOVE" -gt 0 ]; then
          echo "::error::$FILES_ABOVE file(s) exceed the token threshold of ${{ inputs.threshold }}"
          exit 1
        fi
